-- 코드를 입력하세요
SELECT RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS, 
ROUND(RR.REVIEW_SCORE, 2) AS SCORE
FROM REST_INFO RI
JOIN (
    SELECT RR.REST_ID AS REST_ID, AVG(RR.REVIEW_SCORE) AS REVIEW_SCORE
    FROM REST_REVIEW RR
    WHERE RR.REST_ID IN (
        SELECT RI.REST_ID
        FROM REST_INFO RI
        JOIN REST_REVIEW RR
        ON RI.REST_ID = RR.REST_ID
        WHERE RI.ADDRESS LIKE '서울%')
    GROUP BY RR.REST_ID
) AS RR
ON RI.REST_ID = RR.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC


