-- 코드를 입력하세요
SELECT C.CAR_ID, 
       ROUND(AVG(DATEDIFF(C.END_DATE, C.START_DATE)+1), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS C
GROUP BY C.CAR_ID
HAVING AVG(DATEDIFF(C.END_DATE, C.START_DATE)+1) >= 7
ORDER BY AVERAGE_DURATION DESC, C.CAR_ID DESC