-- 코드를 입력하세요
SELECT F.FLAVOR
FROM FIRST_HALF AS F
JOIN (
        SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
        FROM JULY AS J
        GROUP BY J.FLAVOR
    ) AS JJ
ON F.FLAVOR = JJ.FLAVOR
GROUP BY F.FLAVOR
ORDER BY SUM(F.TOTAL_ORDER + JJ.TOTAL_ORDER) DESC
LIMIT 3
;