-- 코드를 작성해주세요
SELECT FI.ID, FNI.FISH_NAME, FI.LENGTH
FROM FISH_INFO AS FI
JOIN FISH_NAME_INFO AS FNI
ON FI.FISH_TYPE = FNI.FISH_TYPE
JOIN (
        SELECT FI.FISH_TYPE, MAX(LENGTH) AS MAX_F2
        FROM FISH_INFO AS FI
        GROUP BY FI.FISH_TYPE
) AS F2
ON F2.FISH_TYPE = FI.FISH_TYPE AND MAX_F2 = FI.LENGTH
ORDER BY FI.ID